<a href="https://colab.research.google.com/github/P9604/TCR_COURSE/blob/master/SES15(10SEP)_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
print(np.__version__)

1.19.5


In [4]:
digit = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [5]:
print(digit)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Different DImensions of array:**

In [12]:
a = np.array(42) #no dimension
b = np.array([1,2,3,5,6])  
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,6,2]]])

In [13]:
#dimensions with rows and cols
print(a.shape , b.shape , c.shape , d.shape)

() (5,) (3, 3) (2, 2, 3)


In [14]:
#dimensions only
print(a.ndim , b.ndim , c.ndim , d.ndim)

0 1 2 3


In [21]:
#1,2,3,4 task is can you create an array of two dimensions with this number
a = np.array([[1,2],[3,4]]) #manually
b = np.array([1,2,3,4],ndmin = 2) #automatically


In [25]:
print(b.ndim)
print(b)
print(a.ndim)
print(a)

2
[[1 2 3 4]]
2
[[1 2]
 [3 4]]


In [39]:
d = np.array([1,2,3,4],ndmin = 1)
print(d)
d = d.reshape((2,2))
print(d)


[1 2 3 4]
[[1 2]
 [3 4]]


In [40]:
val  = np.array([[1,2],[3,4]])
val[0]

array([1, 2])